sudo: false

addons:
  jwt:
    secure: jVSvu9mlFqqifMcAQpEg+rWYDG43wzTovyptz097PQk/JXGX7TKd90aBWyE3ef/Qbjq+OV7PDxSRTUQwuMXhE9+FUYQs6PiW62CmDMwumForaV2NVbmoTREl1gQIgenx++bdWSN+V5ebh6iLj58ZUxZeSAZBsfM6a+G++w5QptU=
env:
  global:
    - SAUCE_USERNAME=snay
    - TRAVIS_NODE_VERSION=6

language: node_js
node_js:
  - "6"

matrix:
  include:
    - env: PLATFORM=browser-chrome
    - env: PLATFORM=browser-firefox
    - env: PLATFORM=browser-safari
    - env: PLATFORM=browser-edge
    - env: PLATFORM=ios-9.3
      os: osx
      osx_image: xcode7.3
    - env: PLATFORM=ios-10.0
      os: osx
      osx_image: xcode7.3
    - env: PLATFORM=android-4.4
      os: linux
      language: android
      jdk: oraclejdk8
      android:
        components:
        - tools
        - build-tools-26.0.2
    - env: PLATFORM=android-5.1
      os: linux
      language: android
      jdk: oraclejdk8
      android:
        components:
        - tools
        - build-tools-26.0.2
    - env: PLATFORM=android-6.0
      os: linux
      language: android
      jdk: oraclejdk8
      android:
        components:
        - tools
        - build-tools-26.0.2
    - env: PLATFORM=android-7.0
      os: linux
      language: android
      jdk: oraclejdk8
      android:
        components:
        - tools
        - build-tools-26.0.2

before_install:
  # `language: android` has no Node.js installed, therefore we need to install it manually
  - if [[ "$PLATFORM" =~ android ]]; then nvm install $TRAVIS_NODE_VERSION; fi
  - node --version
  - if [[ "$PLATFORM" =~ android ]]; then gradle --version; fi
  - if [[ "$PLATFORM" =~ ios ]]; then npm install -g ios-deploy; fi
  - if [[ "$PLATFORM" =~ android ]]; then echo y | android update sdk -u --filter android-22,android-23,android-24,android-25,android-26,android-27,android-28; fi
  - npm install -g cordova-paramedic@https://github.com/apache/cordova-paramedic.git
  - npm install -g cordova
install:
  - npm install

script:
  - npm test
  - cordova-paramedic --config pr/$PLATFORM --plugin $TRAVIS_BUILD_DIR --shouldUseSauce --buildName travis-$TRAVIS_REPO_SLUG-$TRAVIS_JOB_NUMBER
